/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 14
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_module = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_const = 4,
  anon_sym_COLON = 5,
  anon_sym_var = 6,
  anon_sym_val = 7,
  anon_sym_EQ = 8,
  anon_sym_type = 9,
  anon_sym_int = 10,
  anon_sym_bool = 11,
  anon_sym_str = 12,
  anon_sym_Set = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_List = 16,
  anon_sym_LPAREN = 17,
  anon_sym_COMMA = 18,
  anon_sym_RPAREN = 19,
  anon_sym_DASH_GT = 20,
  anon_sym_PLUS = 21,
  anon_sym_STAR = 22,
  sym_integer_literal = 23,
  anon_sym_true = 24,
  anon_sym_false = 25,
  sym_string_literal = 26,
  sym_identifier = 27,
  sym_source_file = 28,
  sym_module_definition = 29,
  sym__declaration = 30,
  sym_constant_declaration = 31,
  sym_variable_declaration = 32,
  sym_value_definition = 33,
  sym_type_alias_declaration = 34,
  sym_uninterpreted_type_declaration = 35,
  sym__type = 36,
  sym_primitive_type = 37,
  sym_named_type = 38,
  sym_set_type = 39,
  sym_list_type = 40,
  sym_tuple_type = 41,
  sym_parenthesized_type = 42,
  sym_record_type = 43,
  sym_record_type_field = 44,
  sym_function_type = 45,
  sym__expression = 46,
  sym_binary_expression = 47,
  sym_boolean_literal = 48,
  sym_name_reference = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym_module_definition_repeat1 = 51,
  aux_sym_tuple_type_repeat1 = 52,
  aux_sym_record_type_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_module] = "module",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_const] = "const",
  [anon_sym_COLON] = ":",
  [anon_sym_var] = "var",
  [anon_sym_val] = "val",
  [anon_sym_EQ] = "=",
  [anon_sym_type] = "type",
  [anon_sym_int] = "int",
  [anon_sym_bool] = "bool",
  [anon_sym_str] = "str",
  [anon_sym_Set] = "Set",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_List] = "List",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [sym_integer_literal] = "integer_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string_literal] = "string_literal",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_module_definition] = "module_definition",
  [sym__declaration] = "_declaration",
  [sym_constant_declaration] = "constant_declaration",
  [sym_variable_declaration] = "variable_declaration",
  [sym_value_definition] = "value_definition",
  [sym_type_alias_declaration] = "type_alias_declaration",
  [sym_uninterpreted_type_declaration] = "uninterpreted_type_declaration",
  [sym__type] = "_type",
  [sym_primitive_type] = "primitive_type",
  [sym_named_type] = "named_type",
  [sym_set_type] = "set_type",
  [sym_list_type] = "list_type",
  [sym_tuple_type] = "tuple_type",
  [sym_parenthesized_type] = "parenthesized_type",
  [sym_record_type] = "record_type",
  [sym_record_type_field] = "record_type_field",
  [sym_function_type] = "function_type",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_boolean_literal] = "boolean_literal",
  [sym_name_reference] = "name_reference",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_module_definition_repeat1] = "module_definition_repeat1",
  [aux_sym_tuple_type_repeat1] = "tuple_type_repeat1",
  [aux_sym_record_type_repeat1] = "record_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_val] = anon_sym_val,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_Set] = anon_sym_Set,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_List] = anon_sym_List,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_integer_literal] = sym_integer_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string_literal] = sym_string_literal,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_module_definition] = sym_module_definition,
  [sym__declaration] = sym__declaration,
  [sym_constant_declaration] = sym_constant_declaration,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_value_definition] = sym_value_definition,
  [sym_type_alias_declaration] = sym_type_alias_declaration,
  [sym_uninterpreted_type_declaration] = sym_uninterpreted_type_declaration,
  [sym__type] = sym__type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_named_type] = sym_named_type,
  [sym_set_type] = sym_set_type,
  [sym_list_type] = sym_list_type,
  [sym_tuple_type] = sym_tuple_type,
  [sym_parenthesized_type] = sym_parenthesized_type,
  [sym_record_type] = sym_record_type,
  [sym_record_type_field] = sym_record_type_field,
  [sym_function_type] = sym_function_type,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_name_reference] = sym_name_reference,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_module_definition_repeat1] = aux_sym_module_definition_repeat1,
  [aux_sym_tuple_type_repeat1] = aux_sym_tuple_type_repeat1,
  [aux_sym_record_type_repeat1] = aux_sym_record_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_val] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_List] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_module_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_constant_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_value_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_alias_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_uninterpreted_type_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_named_type] = {
    .visible = true,
    .named = true,
  },
  [sym_set_type] = {
    .visible = true,
    .named = true,
  },
  [sym_list_type] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type_field] = {
    .visible = true,
    .named = true,
  },
  [sym_function_type] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_name_reference] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_element = 1,
  field_left = 2,
  field_name = 3,
  field_operator = 4,
  field_parameter = 5,
  field_result = 6,
  field_right = 7,
  field_type = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_element] = "element",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_parameter] = "parameter",
  [field_result] = "result",
  [field_right] = "right",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 3},
  [8] = {.index = 12, .length = 2},
  [9] = {.index = 14, .length = 1},
  [10] = {.index = 15, .length = 2},
  [11] = {.index = 17, .length = 1},
  [12] = {.index = 18, .length = 3},
  [13] = {.index = 21, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_name, 1},
    {field_type, 3},
  [4] =
    {field_name, 1},
    {field_value, 3},
  [6] =
    {field_type, 1},
  [7] =
    {field_parameter, 0},
    {field_result, 2},
  [9] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [12] =
    {field_name, 0},
    {field_type, 2},
  [14] =
    {field_element, 2},
  [15] =
    {field_element, 1},
    {field_element, 3},
  [17] =
    {field_element, 1},
  [18] =
    {field_element, 1},
    {field_element, 3},
    {field_element, 4, .inherited = true},
  [21] =
    {field_element, 0, .inherited = true},
    {field_element, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 2,
        '(', 60,
        ')', 62,
        '*', 65,
        '+', 64,
        ',', 61,
        '-', 4,
        ':', 43,
        '=', 46,
        'L', 13,
        'S', 12,
        '[', 56,
        ']', 57,
        'b', 23,
        'c', 21,
        'f', 5,
        'i', 18,
        'm', 20,
        's', 30,
        't', 25,
        'v', 6,
        '{', 40,
        '}', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == 't') ADVANCE(83);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\\') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(60);
      if (lookahead == 'L') ADVANCE(76);
      if (lookahead == 'S') ADVANCE(75);
      if (lookahead == 'b') ADVANCE(81);
      if (lookahead == 'i') ADVANCE(79);
      if (lookahead == 's') ADVANCE(86);
      if (lookahead == '{') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(63);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(36);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(45);
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(35);
      if (lookahead == 'y') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(34);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 37:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_val);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_str);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_Set);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_Set);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_List);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_List);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 37},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 37},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 37},
  [56] = {.lex_state = 37},
  [57] = {.lex_state = 37},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 37},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 37},
  [67] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_val] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_Set] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_List] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(58),
    [sym_module_definition] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(38),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_module] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(23), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [32] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(51), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [64] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(40), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [96] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(34), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [128] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(33), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [160] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(36), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [192] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(49), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [224] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(43), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [256] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(39), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [288] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(45), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [320] = 6,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_const,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym_val,
    ACTIONS(27), 1,
      anon_sym_type,
    STATE(13), 7,
      sym__declaration,
      sym_constant_declaration,
      sym_variable_declaration,
      sym_value_definition,
      sym_type_alias_declaration,
      sym_uninterpreted_type_declaration,
      aux_sym_module_definition_repeat1,
  [345] = 6,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      anon_sym_const,
    ACTIONS(34), 1,
      anon_sym_var,
    ACTIONS(37), 1,
      anon_sym_val,
    ACTIONS(40), 1,
      anon_sym_type,
    STATE(13), 7,
      sym__declaration,
      sym_constant_declaration,
      sym_variable_declaration,
      sym_value_definition,
      sym_type_alias_declaration,
      sym_uninterpreted_type_declaration,
      aux_sym_module_definition_repeat1,
  [370] = 6,
    ACTIONS(21), 1,
      anon_sym_const,
    ACTIONS(23), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym_val,
    ACTIONS(27), 1,
      anon_sym_type,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(12), 7,
      sym__declaration,
      sym_constant_declaration,
      sym_variable_declaration,
      sym_value_definition,
      sym_type_alias_declaration,
      sym_uninterpreted_type_declaration,
      aux_sym_module_definition_repeat1,
  [395] = 1,
    ACTIONS(45), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [407] = 4,
    ACTIONS(51), 1,
      sym_identifier,
    ACTIONS(47), 2,
      sym_integer_literal,
      sym_string_literal,
    ACTIONS(49), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(30), 4,
      sym__expression,
      sym_binary_expression,
      sym_boolean_literal,
      sym_name_reference,
  [425] = 1,
    ACTIONS(53), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [437] = 1,
    ACTIONS(55), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [449] = 4,
    ACTIONS(51), 1,
      sym_identifier,
    ACTIONS(49), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(57), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(31), 4,
      sym__expression,
      sym_binary_expression,
      sym_boolean_literal,
      sym_name_reference,
  [467] = 4,
    ACTIONS(51), 1,
      sym_identifier,
    ACTIONS(49), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(59), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(32), 4,
      sym__expression,
      sym_binary_expression,
      sym_boolean_literal,
      sym_name_reference,
  [485] = 1,
    ACTIONS(61), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [497] = 1,
    ACTIONS(63), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [509] = 2,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(65), 8,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [523] = 1,
    ACTIONS(69), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [535] = 1,
    ACTIONS(71), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [547] = 1,
    ACTIONS(73), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [559] = 1,
    ACTIONS(75), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [571] = 1,
    ACTIONS(77), 7,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_PLUS,
      anon_sym_STAR,
  [581] = 1,
    ACTIONS(79), 7,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_PLUS,
      anon_sym_STAR,
  [591] = 3,
    ACTIONS(83), 1,
      anon_sym_PLUS,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(81), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [605] = 2,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(87), 6,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_PLUS,
  [617] = 1,
    ACTIONS(87), 7,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_PLUS,
      anon_sym_STAR,
  [627] = 2,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(89), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [638] = 2,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(91), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [649] = 2,
    ACTIONS(95), 1,
      anon_sym_EQ,
    ACTIONS(93), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [660] = 2,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(97), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [671] = 3,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      anon_sym_module,
    STATE(37), 2,
      sym_module_definition,
      aux_sym_source_file_repeat1,
  [682] = 3,
    ACTIONS(5), 1,
      anon_sym_module,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    STATE(37), 2,
      sym_module_definition,
      aux_sym_source_file_repeat1,
  [693] = 4,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(108), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_tuple_type_repeat1,
  [706] = 3,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
  [716] = 3,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    ACTIONS(116), 1,
      anon_sym_COMMA,
    STATE(42), 1,
      aux_sym_record_type_repeat1,
  [726] = 3,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    STATE(42), 1,
      aux_sym_record_type_repeat1,
  [736] = 2,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(123), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [744] = 3,
    ACTIONS(116), 1,
      anon_sym_COMMA,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      aux_sym_record_type_repeat1,
  [754] = 2,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(127), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [762] = 3,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_tuple_type_repeat1,
  [772] = 3,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_tuple_type_repeat1,
  [782] = 2,
    ACTIONS(136), 1,
      sym_identifier,
    STATE(44), 1,
      sym_record_type_field,
  [789] = 2,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(138), 1,
      anon_sym_RBRACK,
  [796] = 1,
    ACTIONS(140), 2,
      ts_builtin_sym_end,
      anon_sym_module,
  [801] = 2,
    ACTIONS(67), 1,
      anon_sym_DASH_GT,
    ACTIONS(142), 1,
      anon_sym_RBRACK,
  [808] = 2,
    ACTIONS(136), 1,
      sym_identifier,
    STATE(53), 1,
      sym_record_type_field,
  [815] = 1,
    ACTIONS(118), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [820] = 1,
    ACTIONS(144), 2,
      ts_builtin_sym_end,
      anon_sym_module,
  [825] = 1,
    ACTIONS(146), 1,
      sym_identifier,
  [829] = 1,
    ACTIONS(148), 1,
      sym_identifier,
  [833] = 1,
    ACTIONS(150), 1,
      sym_identifier,
  [837] = 1,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
  [841] = 1,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
  [845] = 1,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
  [849] = 1,
    ACTIONS(158), 1,
      anon_sym_LBRACK,
  [853] = 1,
    ACTIONS(160), 1,
      anon_sym_COLON,
  [857] = 1,
    ACTIONS(162), 1,
      anon_sym_COLON,
  [861] = 1,
    ACTIONS(164), 1,
      sym_identifier,
  [865] = 1,
    ACTIONS(166), 1,
      anon_sym_COLON,
  [869] = 1,
    ACTIONS(168), 1,
      sym_identifier,
  [873] = 1,
    ACTIONS(170), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 128,
  [SMALL_STATE(7)] = 160,
  [SMALL_STATE(8)] = 192,
  [SMALL_STATE(9)] = 224,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 288,
  [SMALL_STATE(12)] = 320,
  [SMALL_STATE(13)] = 345,
  [SMALL_STATE(14)] = 370,
  [SMALL_STATE(15)] = 395,
  [SMALL_STATE(16)] = 407,
  [SMALL_STATE(17)] = 425,
  [SMALL_STATE(18)] = 437,
  [SMALL_STATE(19)] = 449,
  [SMALL_STATE(20)] = 467,
  [SMALL_STATE(21)] = 485,
  [SMALL_STATE(22)] = 497,
  [SMALL_STATE(23)] = 509,
  [SMALL_STATE(24)] = 523,
  [SMALL_STATE(25)] = 535,
  [SMALL_STATE(26)] = 547,
  [SMALL_STATE(27)] = 559,
  [SMALL_STATE(28)] = 571,
  [SMALL_STATE(29)] = 581,
  [SMALL_STATE(30)] = 591,
  [SMALL_STATE(31)] = 605,
  [SMALL_STATE(32)] = 617,
  [SMALL_STATE(33)] = 627,
  [SMALL_STATE(34)] = 638,
  [SMALL_STATE(35)] = 649,
  [SMALL_STATE(36)] = 660,
  [SMALL_STATE(37)] = 671,
  [SMALL_STATE(38)] = 682,
  [SMALL_STATE(39)] = 693,
  [SMALL_STATE(40)] = 706,
  [SMALL_STATE(41)] = 716,
  [SMALL_STATE(42)] = 726,
  [SMALL_STATE(43)] = 736,
  [SMALL_STATE(44)] = 744,
  [SMALL_STATE(45)] = 754,
  [SMALL_STATE(46)] = 762,
  [SMALL_STATE(47)] = 772,
  [SMALL_STATE(48)] = 782,
  [SMALL_STATE(49)] = 789,
  [SMALL_STATE(50)] = 796,
  [SMALL_STATE(51)] = 801,
  [SMALL_STATE(52)] = 808,
  [SMALL_STATE(53)] = 815,
  [SMALL_STATE(54)] = 820,
  [SMALL_STATE(55)] = 825,
  [SMALL_STATE(56)] = 829,
  [SMALL_STATE(57)] = 833,
  [SMALL_STATE(58)] = 837,
  [SMALL_STATE(59)] = 841,
  [SMALL_STATE(60)] = 845,
  [SMALL_STATE(61)] = 849,
  [SMALL_STATE(62)] = 853,
  [SMALL_STATE(63)] = 857,
  [SMALL_STATE(64)] = 861,
  [SMALL_STATE(65)] = 865,
  [SMALL_STATE(66)] = 869,
  [SMALL_STATE(67)] = 873,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_type, 4, 0, 9),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_type, 1, 0, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_type, 3, 0, 5),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 3, 0, 6),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_type, 4, 0, 9),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 5, 0, 10),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 6, 0, 12),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_reference, 1, 0, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_definition, 4, 0, 4),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 7),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_declaration, 4, 0, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uninterpreted_type_declaration, 2, 0, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_alias_declaration, 4, 0, 4),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type_field, 3, 0, 8),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 11),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 13), SHIFT_REPEAT(11),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 13),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_definition, 5, 0, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_definition, 4, 0, 1),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [152] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_quint(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "quint",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
