/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 91
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 21
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_module = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_const = 4,
  anon_sym_COLON = 5,
  anon_sym_var = 6,
  anon_sym_val = 7,
  anon_sym_EQ = 8,
  anon_sym_type = 9,
  anon_sym_int = 10,
  anon_sym_bool = 11,
  anon_sym_str = 12,
  anon_sym_Set = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_List = 16,
  anon_sym_LPAREN = 17,
  anon_sym_COMMA = 18,
  anon_sym_RPAREN = 19,
  anon_sym_DASH_GT = 20,
  anon_sym_DASH = 21,
  anon_sym_or = 22,
  anon_sym_and = 23,
  anon_sym_EQ_EQ = 24,
  anon_sym_BANG_EQ = 25,
  anon_sym_LT = 26,
  anon_sym_LT_EQ = 27,
  anon_sym_GT = 28,
  anon_sym_GT_EQ = 29,
  anon_sym_PLUS = 30,
  anon_sym_STAR = 31,
  anon_sym_SLASH = 32,
  sym_integer_literal = 33,
  anon_sym_true = 34,
  anon_sym_false = 35,
  sym_string_literal = 36,
  sym_identifier = 37,
  sym_source_file = 38,
  sym_module_definition = 39,
  sym__declaration = 40,
  sym_constant_declaration = 41,
  sym_variable_declaration = 42,
  sym_value_definition = 43,
  sym_type_alias_declaration = 44,
  sym_uninterpreted_type_declaration = 45,
  sym__type = 46,
  sym_primitive_type = 47,
  sym_named_type = 48,
  sym_set_type = 49,
  sym_list_type = 50,
  sym_tuple_type = 51,
  sym_parenthesized_type = 52,
  sym_record_type = 53,
  sym_record_type_field = 54,
  sym_function_type = 55,
  sym__expression = 56,
  sym_call_expression = 57,
  sym_parenthesized_expression = 58,
  sym_unary_expression = 59,
  sym_binary_expression = 60,
  sym_boolean_literal = 61,
  sym_name_reference = 62,
  aux_sym_source_file_repeat1 = 63,
  aux_sym_module_definition_repeat1 = 64,
  aux_sym_tuple_type_repeat1 = 65,
  aux_sym_record_type_repeat1 = 66,
  aux_sym_call_expression_repeat1 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_module] = "module",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_const] = "const",
  [anon_sym_COLON] = ":",
  [anon_sym_var] = "var",
  [anon_sym_val] = "val",
  [anon_sym_EQ] = "=",
  [anon_sym_type] = "type",
  [anon_sym_int] = "int",
  [anon_sym_bool] = "bool",
  [anon_sym_str] = "str",
  [anon_sym_Set] = "Set",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_List] = "List",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_DASH] = "-",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_integer_literal] = "integer_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string_literal] = "string_literal",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_module_definition] = "module_definition",
  [sym__declaration] = "_declaration",
  [sym_constant_declaration] = "constant_declaration",
  [sym_variable_declaration] = "variable_declaration",
  [sym_value_definition] = "value_definition",
  [sym_type_alias_declaration] = "type_alias_declaration",
  [sym_uninterpreted_type_declaration] = "uninterpreted_type_declaration",
  [sym__type] = "_type",
  [sym_primitive_type] = "primitive_type",
  [sym_named_type] = "named_type",
  [sym_set_type] = "set_type",
  [sym_list_type] = "list_type",
  [sym_tuple_type] = "tuple_type",
  [sym_parenthesized_type] = "parenthesized_type",
  [sym_record_type] = "record_type",
  [sym_record_type_field] = "record_type_field",
  [sym_function_type] = "function_type",
  [sym__expression] = "_expression",
  [sym_call_expression] = "call_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_boolean_literal] = "boolean_literal",
  [sym_name_reference] = "name_reference",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_module_definition_repeat1] = "module_definition_repeat1",
  [aux_sym_tuple_type_repeat1] = "tuple_type_repeat1",
  [aux_sym_record_type_repeat1] = "record_type_repeat1",
  [aux_sym_call_expression_repeat1] = "call_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_val] = anon_sym_val,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_Set] = anon_sym_Set,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_List] = anon_sym_List,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_integer_literal] = sym_integer_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string_literal] = sym_string_literal,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_module_definition] = sym_module_definition,
  [sym__declaration] = sym__declaration,
  [sym_constant_declaration] = sym_constant_declaration,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_value_definition] = sym_value_definition,
  [sym_type_alias_declaration] = sym_type_alias_declaration,
  [sym_uninterpreted_type_declaration] = sym_uninterpreted_type_declaration,
  [sym__type] = sym__type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_named_type] = sym_named_type,
  [sym_set_type] = sym_set_type,
  [sym_list_type] = sym_list_type,
  [sym_tuple_type] = sym_tuple_type,
  [sym_parenthesized_type] = sym_parenthesized_type,
  [sym_record_type] = sym_record_type,
  [sym_record_type_field] = sym_record_type_field,
  [sym_function_type] = sym_function_type,
  [sym__expression] = sym__expression,
  [sym_call_expression] = sym_call_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_name_reference] = sym_name_reference,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_module_definition_repeat1] = aux_sym_module_definition_repeat1,
  [aux_sym_tuple_type_repeat1] = aux_sym_tuple_type_repeat1,
  [aux_sym_record_type_repeat1] = aux_sym_record_type_repeat1,
  [aux_sym_call_expression_repeat1] = aux_sym_call_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_val] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_List] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_module_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_constant_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_value_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_alias_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_uninterpreted_type_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_named_type] = {
    .visible = true,
    .named = true,
  },
  [sym_set_type] = {
    .visible = true,
    .named = true,
  },
  [sym_list_type] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type_field] = {
    .visible = true,
    .named = true,
  },
  [sym_function_type] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_name_reference] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_element = 2,
  field_expression = 3,
  field_function = 4,
  field_left = 5,
  field_name = 6,
  field_operand = 7,
  field_operator = 8,
  field_parameter = 9,
  field_result = 10,
  field_right = 11,
  field_type = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_element] = "element",
  [field_expression] = "expression",
  [field_function] = "function",
  [field_left] = "left",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_parameter] = "parameter",
  [field_result] = "result",
  [field_right] = "right",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 3},
  [10] = {.index = 15, .length = 1},
  [11] = {.index = 16, .length = 2},
  [12] = {.index = 18, .length = 1},
  [13] = {.index = 19, .length = 2},
  [14] = {.index = 21, .length = 2},
  [15] = {.index = 23, .length = 1},
  [16] = {.index = 24, .length = 3},
  [17] = {.index = 27, .length = 2},
  [18] = {.index = 29, .length = 1},
  [19] = {.index = 30, .length = 3},
  [20] = {.index = 33, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_name, 1},
    {field_type, 3},
  [4] =
    {field_name, 1},
    {field_value, 3},
  [6] =
    {field_operand, 1},
    {field_operator, 0},
  [8] =
    {field_type, 1},
  [9] =
    {field_parameter, 0},
    {field_result, 2},
  [11] =
    {field_expression, 1},
  [12] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [15] =
    {field_function, 0},
  [16] =
    {field_name, 0},
    {field_type, 2},
  [18] =
    {field_element, 2},
  [19] =
    {field_argument, 2},
    {field_function, 0},
  [21] =
    {field_element, 1},
    {field_element, 3},
  [23] =
    {field_argument, 1},
  [24] =
    {field_argument, 2},
    {field_argument, 3, .inherited = true},
    {field_function, 0},
  [27] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
  [29] =
    {field_element, 1},
  [30] =
    {field_element, 1},
    {field_element, 3},
    {field_element, 4, .inherited = true},
  [33] =
    {field_element, 0, .inherited = true},
    {field_element, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(46);
      ADVANCE_MAP(
        '!', 6,
        '"', 3,
        '(', 69,
        ')', 71,
        '*', 84,
        '+', 83,
        ',', 70,
        '-', 74,
        '/', 85,
        ':', 51,
        '<', 79,
        '=', 55,
        '>', 81,
        'L', 18,
        'S', 17,
        '[', 65,
        ']', 66,
        'a', 23,
        'b', 29,
        'c', 28,
        'f', 9,
        'i', 24,
        'm', 26,
        'o', 31,
        's', 41,
        't', 32,
        'v', 10,
        '{', 48,
        '}', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 6,
        '(', 69,
        ')', 71,
        '*', 84,
        '+', 83,
        ',', 70,
        '-', 73,
        '/', 85,
        '<', 79,
        '=', 7,
        '>', 81,
        'a', 23,
        'c', 28,
        'o', 31,
        't', 44,
        'v', 10,
        '}', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(69);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == '-') ADVANCE(73);
      if (lookahead == 'f') ADVANCE(92);
      if (lookahead == 't') ADVANCE(103);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\\') ADVANCE(3);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '(', 69,
        ')', 71,
        ',', 70,
        '-', 8,
        '=', 54,
        'L', 96,
        'S', 95,
        ']', 66,
        'b', 101,
        'i', 99,
        's', 106,
        '{', 48,
        '}', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        ')', 71,
        ',', 70,
        '-', 8,
        '=', 54,
        ']', 66,
        'c', 28,
        't', 44,
        'v', 10,
        '}', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(78);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(77);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(72);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(76);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(43);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(53);
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(59);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(42);
      if (lookahead == 'y') ADVANCE(30);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(61);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 42:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 44:
      if (lookahead == 'y') ADVANCE(30);
      END_STATE();
    case 45:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_val);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(77);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_str);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_Set);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_Set);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_List);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_List);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(72);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 5},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 45},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 45},
  [77] = {.lex_state = 4},
  [78] = {.lex_state = 45},
  [79] = {.lex_state = 45},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 45},
  [82] = {.lex_state = 45},
  [83] = {.lex_state = 45},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_val] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_Set] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_List] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(80),
    [sym_module_definition] = STATE(58),
    [aux_sym_source_file_repeat1] = STATE(58),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_module] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(9), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(7), 18,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [25] = 3,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(11), 17,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [52] = 2,
    ACTIONS(19), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(17), 17,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [76] = 2,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 17,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [100] = 7,
    ACTIONS(29), 1,
      anon_sym_and,
    ACTIONS(27), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(31), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(25), 8,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_or,
  [134] = 2,
    ACTIONS(41), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 17,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [158] = 3,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 15,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [184] = 5,
    ACTIONS(27), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(25), 11,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [214] = 6,
    ACTIONS(27), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(31), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(25), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [246] = 2,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 17,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [270] = 4,
    ACTIONS(27), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 13,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [298] = 2,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 17,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [322] = 2,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 17,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [346] = 2,
    ACTIONS(55), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 17,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [370] = 7,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_Set,
    ACTIONS(63), 1,
      anon_sym_List,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(59), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(55), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [402] = 7,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_Set,
    ACTIONS(63), 1,
      anon_sym_List,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(59), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(57), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [434] = 7,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_Set,
    ACTIONS(63), 1,
      anon_sym_List,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(59), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(62), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [466] = 7,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_Set,
    ACTIONS(63), 1,
      anon_sym_List,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(59), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(56), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [498] = 7,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_Set,
    ACTIONS(63), 1,
      anon_sym_List,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(59), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(77), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [530] = 7,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_Set,
    ACTIONS(63), 1,
      anon_sym_List,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(59), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(75), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [562] = 8,
    ACTIONS(29), 1,
      anon_sym_and,
    ACTIONS(71), 1,
      anon_sym_or,
    ACTIONS(27), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(31), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [596] = 7,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_Set,
    ACTIONS(63), 1,
      anon_sym_List,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(59), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(47), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [628] = 7,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_Set,
    ACTIONS(63), 1,
      anon_sym_List,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(59), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(60), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [660] = 7,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_Set,
    ACTIONS(63), 1,
      anon_sym_List,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(59), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(63), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [692] = 7,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_Set,
    ACTIONS(63), 1,
      anon_sym_List,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(59), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(65), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [724] = 10,
    ACTIONS(29), 1,
      anon_sym_and,
    ACTIONS(71), 1,
      anon_sym_or,
    ACTIONS(73), 1,
      anon_sym_COMMA,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_call_expression_repeat1,
    ACTIONS(27), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(31), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [760] = 8,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(3), 1,
      sym_name_reference,
    ACTIONS(83), 2,
      sym_integer_literal,
      sym_string_literal,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 6,
      sym__expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
  [792] = 7,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(3), 1,
      sym_name_reference,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(89), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(40), 6,
      sym__expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
  [821] = 7,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(3), 1,
      sym_name_reference,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(91), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(8), 6,
      sym__expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
  [850] = 7,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(3), 1,
      sym_name_reference,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(93), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(6), 6,
      sym__expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
  [879] = 7,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(3), 1,
      sym_name_reference,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(95), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(9), 6,
      sym__expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
  [908] = 7,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(3), 1,
      sym_name_reference,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(97), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(12), 6,
      sym__expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
  [937] = 7,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(3), 1,
      sym_name_reference,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(99), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(13), 6,
      sym__expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
  [966] = 7,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(3), 1,
      sym_name_reference,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(101), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(10), 6,
      sym__expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
  [995] = 7,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(3), 1,
      sym_name_reference,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(103), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(39), 6,
      sym__expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
  [1024] = 7,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(3), 1,
      sym_name_reference,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(105), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(4), 6,
      sym__expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
  [1053] = 7,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(3), 1,
      sym_name_reference,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(107), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(22), 6,
      sym__expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
  [1082] = 8,
    ACTIONS(29), 1,
      anon_sym_and,
    ACTIONS(71), 1,
      anon_sym_or,
    ACTIONS(27), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(31), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(109), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1113] = 8,
    ACTIONS(29), 1,
      anon_sym_and,
    ACTIONS(71), 1,
      anon_sym_or,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    ACTIONS(27), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(31), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1143] = 6,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    ACTIONS(115), 1,
      anon_sym_const,
    ACTIONS(117), 1,
      anon_sym_var,
    ACTIONS(119), 1,
      anon_sym_val,
    ACTIONS(121), 1,
      anon_sym_type,
    STATE(43), 7,
      sym__declaration,
      sym_constant_declaration,
      sym_variable_declaration,
      sym_value_definition,
      sym_type_alias_declaration,
      sym_uninterpreted_type_declaration,
      aux_sym_module_definition_repeat1,
  [1168] = 6,
    ACTIONS(123), 1,
      anon_sym_RBRACE,
    ACTIONS(125), 1,
      anon_sym_const,
    ACTIONS(128), 1,
      anon_sym_var,
    ACTIONS(131), 1,
      anon_sym_val,
    ACTIONS(134), 1,
      anon_sym_type,
    STATE(42), 7,
      sym__declaration,
      sym_constant_declaration,
      sym_variable_declaration,
      sym_value_definition,
      sym_type_alias_declaration,
      sym_uninterpreted_type_declaration,
      aux_sym_module_definition_repeat1,
  [1193] = 6,
    ACTIONS(115), 1,
      anon_sym_const,
    ACTIONS(117), 1,
      anon_sym_var,
    ACTIONS(119), 1,
      anon_sym_val,
    ACTIONS(121), 1,
      anon_sym_type,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    STATE(42), 7,
      sym__declaration,
      sym_constant_declaration,
      sym_variable_declaration,
      sym_value_definition,
      sym_type_alias_declaration,
      sym_uninterpreted_type_declaration,
      aux_sym_module_definition_repeat1,
  [1218] = 1,
    ACTIONS(139), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [1230] = 1,
    ACTIONS(141), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [1242] = 1,
    ACTIONS(143), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [1254] = 2,
    ACTIONS(147), 1,
      anon_sym_DASH_GT,
    ACTIONS(145), 8,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1268] = 1,
    ACTIONS(149), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [1280] = 1,
    ACTIONS(151), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [1292] = 1,
    ACTIONS(153), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [1304] = 1,
    ACTIONS(155), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [1316] = 1,
    ACTIONS(157), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [1328] = 1,
    ACTIONS(159), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [1340] = 2,
    ACTIONS(163), 1,
      anon_sym_EQ,
    ACTIONS(161), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [1351] = 2,
    ACTIONS(147), 1,
      anon_sym_DASH_GT,
    ACTIONS(165), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [1362] = 2,
    ACTIONS(147), 1,
      anon_sym_DASH_GT,
    ACTIONS(167), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [1373] = 2,
    ACTIONS(147), 1,
      anon_sym_DASH_GT,
    ACTIONS(169), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [1384] = 3,
    ACTIONS(5), 1,
      anon_sym_module,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    STATE(59), 2,
      sym_module_definition,
      aux_sym_source_file_repeat1,
  [1395] = 3,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 1,
      anon_sym_module,
    STATE(59), 2,
      sym_module_definition,
      aux_sym_source_file_repeat1,
  [1406] = 4,
    ACTIONS(147), 1,
      anon_sym_DASH_GT,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym_tuple_type_repeat1,
  [1419] = 3,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_tuple_type_repeat1,
  [1429] = 3,
    ACTIONS(147), 1,
      anon_sym_DASH_GT,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
  [1439] = 2,
    ACTIONS(147), 1,
      anon_sym_DASH_GT,
    ACTIONS(188), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1447] = 3,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_record_type_repeat1,
  [1457] = 2,
    ACTIONS(147), 1,
      anon_sym_DASH_GT,
    ACTIONS(195), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1465] = 3,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_record_type_repeat1,
  [1475] = 3,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_record_type_repeat1,
  [1485] = 3,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_call_expression_repeat1,
  [1495] = 3,
    ACTIONS(73), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_call_expression_repeat1,
  [1505] = 3,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_tuple_type_repeat1,
  [1515] = 2,
    ACTIONS(215), 1,
      sym_identifier,
    STATE(67), 1,
      sym_record_type_field,
  [1522] = 1,
    ACTIONS(217), 2,
      ts_builtin_sym_end,
      anon_sym_module,
  [1527] = 1,
    ACTIONS(190), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1532] = 1,
    ACTIONS(219), 2,
      ts_builtin_sym_end,
      anon_sym_module,
  [1537] = 2,
    ACTIONS(147), 1,
      anon_sym_DASH_GT,
    ACTIONS(221), 1,
      anon_sym_RBRACK,
  [1544] = 2,
    ACTIONS(215), 1,
      sym_identifier,
    STATE(73), 1,
      sym_record_type_field,
  [1551] = 2,
    ACTIONS(147), 1,
      anon_sym_DASH_GT,
    ACTIONS(223), 1,
      anon_sym_RBRACK,
  [1558] = 1,
    ACTIONS(225), 1,
      sym_identifier,
  [1562] = 1,
    ACTIONS(227), 1,
      sym_identifier,
  [1566] = 1,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
  [1570] = 1,
    ACTIONS(231), 1,
      sym_identifier,
  [1574] = 1,
    ACTIONS(233), 1,
      sym_identifier,
  [1578] = 1,
    ACTIONS(235), 1,
      sym_identifier,
  [1582] = 1,
    ACTIONS(237), 1,
      anon_sym_LBRACK,
  [1586] = 1,
    ACTIONS(239), 1,
      anon_sym_COLON,
  [1590] = 1,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
  [1594] = 1,
    ACTIONS(243), 1,
      anon_sym_COLON,
  [1598] = 1,
    ACTIONS(245), 1,
      anon_sym_COLON,
  [1602] = 1,
    ACTIONS(247), 1,
      anon_sym_LBRACK,
  [1606] = 1,
    ACTIONS(249), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 76,
  [SMALL_STATE(6)] = 100,
  [SMALL_STATE(7)] = 134,
  [SMALL_STATE(8)] = 158,
  [SMALL_STATE(9)] = 184,
  [SMALL_STATE(10)] = 214,
  [SMALL_STATE(11)] = 246,
  [SMALL_STATE(12)] = 270,
  [SMALL_STATE(13)] = 298,
  [SMALL_STATE(14)] = 322,
  [SMALL_STATE(15)] = 346,
  [SMALL_STATE(16)] = 370,
  [SMALL_STATE(17)] = 402,
  [SMALL_STATE(18)] = 434,
  [SMALL_STATE(19)] = 466,
  [SMALL_STATE(20)] = 498,
  [SMALL_STATE(21)] = 530,
  [SMALL_STATE(22)] = 562,
  [SMALL_STATE(23)] = 596,
  [SMALL_STATE(24)] = 628,
  [SMALL_STATE(25)] = 660,
  [SMALL_STATE(26)] = 692,
  [SMALL_STATE(27)] = 724,
  [SMALL_STATE(28)] = 760,
  [SMALL_STATE(29)] = 792,
  [SMALL_STATE(30)] = 821,
  [SMALL_STATE(31)] = 850,
  [SMALL_STATE(32)] = 879,
  [SMALL_STATE(33)] = 908,
  [SMALL_STATE(34)] = 937,
  [SMALL_STATE(35)] = 966,
  [SMALL_STATE(36)] = 995,
  [SMALL_STATE(37)] = 1024,
  [SMALL_STATE(38)] = 1053,
  [SMALL_STATE(39)] = 1082,
  [SMALL_STATE(40)] = 1113,
  [SMALL_STATE(41)] = 1143,
  [SMALL_STATE(42)] = 1168,
  [SMALL_STATE(43)] = 1193,
  [SMALL_STATE(44)] = 1218,
  [SMALL_STATE(45)] = 1230,
  [SMALL_STATE(46)] = 1242,
  [SMALL_STATE(47)] = 1254,
  [SMALL_STATE(48)] = 1268,
  [SMALL_STATE(49)] = 1280,
  [SMALL_STATE(50)] = 1292,
  [SMALL_STATE(51)] = 1304,
  [SMALL_STATE(52)] = 1316,
  [SMALL_STATE(53)] = 1328,
  [SMALL_STATE(54)] = 1340,
  [SMALL_STATE(55)] = 1351,
  [SMALL_STATE(56)] = 1362,
  [SMALL_STATE(57)] = 1373,
  [SMALL_STATE(58)] = 1384,
  [SMALL_STATE(59)] = 1395,
  [SMALL_STATE(60)] = 1406,
  [SMALL_STATE(61)] = 1419,
  [SMALL_STATE(62)] = 1429,
  [SMALL_STATE(63)] = 1439,
  [SMALL_STATE(64)] = 1447,
  [SMALL_STATE(65)] = 1457,
  [SMALL_STATE(66)] = 1465,
  [SMALL_STATE(67)] = 1475,
  [SMALL_STATE(68)] = 1485,
  [SMALL_STATE(69)] = 1495,
  [SMALL_STATE(70)] = 1505,
  [SMALL_STATE(71)] = 1515,
  [SMALL_STATE(72)] = 1522,
  [SMALL_STATE(73)] = 1527,
  [SMALL_STATE(74)] = 1532,
  [SMALL_STATE(75)] = 1537,
  [SMALL_STATE(76)] = 1544,
  [SMALL_STATE(77)] = 1551,
  [SMALL_STATE(78)] = 1558,
  [SMALL_STATE(79)] = 1562,
  [SMALL_STATE(80)] = 1566,
  [SMALL_STATE(81)] = 1570,
  [SMALL_STATE(82)] = 1574,
  [SMALL_STATE(83)] = 1578,
  [SMALL_STATE(84)] = 1582,
  [SMALL_STATE(85)] = 1586,
  [SMALL_STATE(86)] = 1590,
  [SMALL_STATE(87)] = 1594,
  [SMALL_STATE(88)] = 1598,
  [SMALL_STATE(89)] = 1602,
  [SMALL_STATE(90)] = 1606,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_reference, 1, 0, 2),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name_reference, 1, 0, 2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 5),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 5),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 9),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 8),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 8),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 9),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, 0, 13),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 4, 0, 13),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, 0, 10),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 3, 0, 10),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 5, 0, 16),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 5, 0, 16),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_definition, 4, 0, 4),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2, 0, 15),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_type, 3, 0, 6),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 6, 0, 19),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 3, 0, 7),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_type, 1, 0, 2),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_type, 4, 0, 12),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_type, 4, 0, 12),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 5, 0, 14),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uninterpreted_type_declaration, 2, 0, 1),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 3),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_alias_declaration, 4, 0, 4),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_declaration, 4, 0, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type_field, 3, 0, 11),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 18),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2, 0, 17), SHIFT_REPEAT(36),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2, 0, 17),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 20), SHIFT_REPEAT(26),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 20),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_definition, 5, 0, 1),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_definition, 4, 0, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [229] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_quint(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "quint",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
