/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 16
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_module = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_const = 4,
  anon_sym_COLON = 5,
  anon_sym_var = 6,
  anon_sym_val = 7,
  anon_sym_EQ = 8,
  anon_sym_type = 9,
  anon_sym_int = 10,
  anon_sym_bool = 11,
  anon_sym_str = 12,
  anon_sym_Set = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_List = 16,
  anon_sym_LPAREN = 17,
  anon_sym_COMMA = 18,
  anon_sym_RPAREN = 19,
  anon_sym_DASH_GT = 20,
  anon_sym_DASH = 21,
  anon_sym_EQ_EQ = 22,
  anon_sym_BANG_EQ = 23,
  anon_sym_PLUS = 24,
  anon_sym_STAR = 25,
  anon_sym_SLASH = 26,
  sym_integer_literal = 27,
  anon_sym_true = 28,
  anon_sym_false = 29,
  sym_string_literal = 30,
  sym_identifier = 31,
  sym_source_file = 32,
  sym_module_definition = 33,
  sym__declaration = 34,
  sym_constant_declaration = 35,
  sym_variable_declaration = 36,
  sym_value_definition = 37,
  sym_type_alias_declaration = 38,
  sym_uninterpreted_type_declaration = 39,
  sym__type = 40,
  sym_primitive_type = 41,
  sym_named_type = 42,
  sym_set_type = 43,
  sym_list_type = 44,
  sym_tuple_type = 45,
  sym_parenthesized_type = 46,
  sym_record_type = 47,
  sym_record_type_field = 48,
  sym_function_type = 49,
  sym__expression = 50,
  sym_parenthesized_expression = 51,
  sym_unary_expression = 52,
  sym_binary_expression = 53,
  sym_boolean_literal = 54,
  sym_name_reference = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_module_definition_repeat1 = 57,
  aux_sym_tuple_type_repeat1 = 58,
  aux_sym_record_type_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_module] = "module",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_const] = "const",
  [anon_sym_COLON] = ":",
  [anon_sym_var] = "var",
  [anon_sym_val] = "val",
  [anon_sym_EQ] = "=",
  [anon_sym_type] = "type",
  [anon_sym_int] = "int",
  [anon_sym_bool] = "bool",
  [anon_sym_str] = "str",
  [anon_sym_Set] = "Set",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_List] = "List",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_integer_literal] = "integer_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string_literal] = "string_literal",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_module_definition] = "module_definition",
  [sym__declaration] = "_declaration",
  [sym_constant_declaration] = "constant_declaration",
  [sym_variable_declaration] = "variable_declaration",
  [sym_value_definition] = "value_definition",
  [sym_type_alias_declaration] = "type_alias_declaration",
  [sym_uninterpreted_type_declaration] = "uninterpreted_type_declaration",
  [sym__type] = "_type",
  [sym_primitive_type] = "primitive_type",
  [sym_named_type] = "named_type",
  [sym_set_type] = "set_type",
  [sym_list_type] = "list_type",
  [sym_tuple_type] = "tuple_type",
  [sym_parenthesized_type] = "parenthesized_type",
  [sym_record_type] = "record_type",
  [sym_record_type_field] = "record_type_field",
  [sym_function_type] = "function_type",
  [sym__expression] = "_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_boolean_literal] = "boolean_literal",
  [sym_name_reference] = "name_reference",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_module_definition_repeat1] = "module_definition_repeat1",
  [aux_sym_tuple_type_repeat1] = "tuple_type_repeat1",
  [aux_sym_record_type_repeat1] = "record_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_val] = anon_sym_val,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_Set] = anon_sym_Set,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_List] = anon_sym_List,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_integer_literal] = sym_integer_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string_literal] = sym_string_literal,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_module_definition] = sym_module_definition,
  [sym__declaration] = sym__declaration,
  [sym_constant_declaration] = sym_constant_declaration,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_value_definition] = sym_value_definition,
  [sym_type_alias_declaration] = sym_type_alias_declaration,
  [sym_uninterpreted_type_declaration] = sym_uninterpreted_type_declaration,
  [sym__type] = sym__type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_named_type] = sym_named_type,
  [sym_set_type] = sym_set_type,
  [sym_list_type] = sym_list_type,
  [sym_tuple_type] = sym_tuple_type,
  [sym_parenthesized_type] = sym_parenthesized_type,
  [sym_record_type] = sym_record_type,
  [sym_record_type_field] = sym_record_type_field,
  [sym_function_type] = sym_function_type,
  [sym__expression] = sym__expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_name_reference] = sym_name_reference,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_module_definition_repeat1] = aux_sym_module_definition_repeat1,
  [aux_sym_tuple_type_repeat1] = aux_sym_tuple_type_repeat1,
  [aux_sym_record_type_repeat1] = aux_sym_record_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_val] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_List] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_module_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_constant_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_value_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_alias_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_uninterpreted_type_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_named_type] = {
    .visible = true,
    .named = true,
  },
  [sym_set_type] = {
    .visible = true,
    .named = true,
  },
  [sym_list_type] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type_field] = {
    .visible = true,
    .named = true,
  },
  [sym_function_type] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_name_reference] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_element = 1,
  field_expression = 2,
  field_left = 3,
  field_name = 4,
  field_operand = 5,
  field_operator = 6,
  field_parameter = 7,
  field_result = 8,
  field_right = 9,
  field_type = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_element] = "element",
  [field_expression] = "expression",
  [field_left] = "left",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_parameter] = "parameter",
  [field_result] = "result",
  [field_right] = "right",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 3},
  [10] = {.index = 15, .length = 2},
  [11] = {.index = 17, .length = 1},
  [12] = {.index = 18, .length = 2},
  [13] = {.index = 20, .length = 1},
  [14] = {.index = 21, .length = 3},
  [15] = {.index = 24, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_name, 1},
    {field_type, 3},
  [4] =
    {field_name, 1},
    {field_value, 3},
  [6] =
    {field_operand, 1},
    {field_operator, 0},
  [8] =
    {field_type, 1},
  [9] =
    {field_parameter, 0},
    {field_result, 2},
  [11] =
    {field_expression, 1},
  [12] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [15] =
    {field_name, 0},
    {field_type, 2},
  [17] =
    {field_element, 2},
  [18] =
    {field_element, 1},
    {field_element, 3},
  [20] =
    {field_element, 1},
  [21] =
    {field_element, 1},
    {field_element, 3},
    {field_element, 4, .inherited = true},
  [24] =
    {field_element, 0, .inherited = true},
    {field_element, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(43);
      ADVANCE_MAP(
        '!', 6,
        '"', 4,
        '(', 66,
        ')', 68,
        '*', 75,
        '+', 74,
        ',', 67,
        '-', 71,
        '/', 76,
        ':', 48,
        '=', 52,
        'L', 17,
        'S', 16,
        '[', 62,
        ']', 63,
        'b', 27,
        'c', 25,
        'f', 9,
        'i', 22,
        'm', 24,
        's', 34,
        't', 29,
        'v', 10,
        '{', 45,
        '}', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 6,
        '(', 66,
        ')', 68,
        '*', 75,
        '+', 74,
        '-', 70,
        '/', 76,
        '=', 7,
        'L', 87,
        'S', 86,
        'b', 92,
        'i', 90,
        's', 97,
        '{', 45,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 6,
        ')', 68,
        '*', 75,
        '+', 74,
        '-', 70,
        '/', 76,
        '=', 7,
        'c', 25,
        't', 41,
        'v', 10,
        '}', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '(') ADVANCE(66);
      if (lookahead == '-') ADVANCE(70);
      if (lookahead == '=') ADVANCE(51);
      if (lookahead == 'f') ADVANCE(83);
      if (lookahead == 't') ADVANCE(94);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\\') ADVANCE(4);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        ')', 68,
        ',', 67,
        '-', 8,
        '=', 51,
        ']', 63,
        'c', 25,
        't', 41,
        'v', 10,
        '}', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(73);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(72);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(69);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(40);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(50);
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(13);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(39);
      if (lookahead == 'y') ADVANCE(28);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 40:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 41:
      if (lookahead == 'y') ADVANCE(28);
      END_STATE();
    case 42:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_val);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(72);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_str);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_Set);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_Set);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_List);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_List);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(69);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 42},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 42},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 42},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 42},
  [70] = {.lex_state = 42},
  [71] = {.lex_state = 42},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 42},
  [74] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_val] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_Set] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_List] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(62),
    [sym_module_definition] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(45),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_module] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(40), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [32] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(41), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [64] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(42), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [96] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(51), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [128] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(59), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [160] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(56), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [192] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(34), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [224] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(50), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [256] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(48), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [288] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_Set,
    ACTIONS(13), 1,
      anon_sym_List,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(9), 3,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_str,
    STATE(44), 9,
      sym__type,
      sym_primitive_type,
      sym_named_type,
      sym_set_type,
      sym_list_type,
      sym_tuple_type,
      sym_parenthesized_type,
      sym_record_type,
      sym_function_type,
  [320] = 6,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(23), 2,
      sym_integer_literal,
      sym_string_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(28), 6,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
      sym_name_reference,
  [346] = 6,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(39), 6,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
      sym_name_reference,
  [372] = 6,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(31), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(21), 6,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
      sym_name_reference,
  [398] = 6,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(33), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(27), 6,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
      sym_name_reference,
  [424] = 6,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(35), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(25), 6,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
      sym_name_reference,
  [450] = 6,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(37), 2,
      sym_integer_literal,
      sym_string_literal,
    STATE(24), 6,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean_literal,
      sym_name_reference,
  [476] = 6,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    ACTIONS(41), 1,
      anon_sym_const,
    ACTIONS(43), 1,
      anon_sym_var,
    ACTIONS(45), 1,
      anon_sym_val,
    ACTIONS(47), 1,
      anon_sym_type,
    STATE(22), 7,
      sym__declaration,
      sym_constant_declaration,
      sym_variable_declaration,
      sym_value_definition,
      sym_type_alias_declaration,
      sym_uninterpreted_type_declaration,
      aux_sym_module_definition_repeat1,
  [501] = 1,
    ACTIONS(49), 12,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [516] = 1,
    ACTIONS(51), 12,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [531] = 1,
    ACTIONS(53), 12,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [546] = 6,
    ACTIONS(41), 1,
      anon_sym_const,
    ACTIONS(43), 1,
      anon_sym_var,
    ACTIONS(45), 1,
      anon_sym_val,
    ACTIONS(47), 1,
      anon_sym_type,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(26), 7,
      sym__declaration,
      sym_constant_declaration,
      sym_variable_declaration,
      sym_value_definition,
      sym_type_alias_declaration,
      sym_uninterpreted_type_declaration,
      aux_sym_module_definition_repeat1,
  [571] = 1,
    ACTIONS(57), 12,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [586] = 3,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(63), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(59), 8,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [605] = 1,
    ACTIONS(59), 12,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [620] = 6,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(67), 1,
      anon_sym_const,
    ACTIONS(70), 1,
      anon_sym_var,
    ACTIONS(73), 1,
      anon_sym_val,
    ACTIONS(76), 1,
      anon_sym_type,
    STATE(26), 7,
      sym__declaration,
      sym_constant_declaration,
      sym_variable_declaration,
      sym_value_definition,
      sym_type_alias_declaration,
      sym_uninterpreted_type_declaration,
      aux_sym_module_definition_repeat1,
  [645] = 2,
    ACTIONS(63), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(59), 10,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_PLUS,
  [662] = 4,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(63), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(79), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [682] = 1,
    ACTIONS(83), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [694] = 1,
    ACTIONS(85), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [706] = 1,
    ACTIONS(87), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [718] = 1,
    ACTIONS(89), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [730] = 1,
    ACTIONS(91), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [742] = 2,
    ACTIONS(95), 1,
      anon_sym_DASH_GT,
    ACTIONS(93), 8,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [756] = 1,
    ACTIONS(97), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [768] = 1,
    ACTIONS(99), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [780] = 1,
    ACTIONS(101), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [792] = 1,
    ACTIONS(103), 9,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
  [804] = 4,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(63), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(81), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [820] = 2,
    ACTIONS(95), 1,
      anon_sym_DASH_GT,
    ACTIONS(107), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [831] = 2,
    ACTIONS(95), 1,
      anon_sym_DASH_GT,
    ACTIONS(109), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [842] = 2,
    ACTIONS(95), 1,
      anon_sym_DASH_GT,
    ACTIONS(111), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [853] = 2,
    ACTIONS(115), 1,
      anon_sym_EQ,
    ACTIONS(113), 5,
      anon_sym_RBRACE,
      anon_sym_const,
      anon_sym_var,
      anon_sym_val,
      anon_sym_type,
  [864] = 4,
    ACTIONS(95), 1,
      anon_sym_DASH_GT,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_tuple_type_repeat1,
  [877] = 3,
    ACTIONS(5), 1,
      anon_sym_module,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    STATE(46), 2,
      sym_module_definition,
      aux_sym_source_file_repeat1,
  [888] = 3,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 1,
      anon_sym_module,
    STATE(46), 2,
      sym_module_definition,
      aux_sym_source_file_repeat1,
  [899] = 3,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_record_type_repeat1,
  [909] = 2,
    ACTIONS(95), 1,
      anon_sym_DASH_GT,
    ACTIONS(132), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [917] = 3,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    STATE(47), 1,
      aux_sym_record_type_repeat1,
  [927] = 2,
    ACTIONS(95), 1,
      anon_sym_DASH_GT,
    ACTIONS(136), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [935] = 3,
    ACTIONS(95), 1,
      anon_sym_DASH_GT,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
  [945] = 3,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_tuple_type_repeat1,
  [955] = 3,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_record_type_repeat1,
  [965] = 3,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_tuple_type_repeat1,
  [975] = 2,
    ACTIONS(154), 1,
      sym_identifier,
    STATE(49), 1,
      sym_record_type_field,
  [982] = 2,
    ACTIONS(95), 1,
      anon_sym_DASH_GT,
    ACTIONS(156), 1,
      anon_sym_RBRACK,
  [989] = 2,
    ACTIONS(154), 1,
      sym_identifier,
    STATE(61), 1,
      sym_record_type_field,
  [996] = 1,
    ACTIONS(158), 2,
      ts_builtin_sym_end,
      anon_sym_module,
  [1001] = 2,
    ACTIONS(95), 1,
      anon_sym_DASH_GT,
    ACTIONS(160), 1,
      anon_sym_RBRACK,
  [1008] = 1,
    ACTIONS(162), 2,
      ts_builtin_sym_end,
      anon_sym_module,
  [1013] = 1,
    ACTIONS(144), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1018] = 1,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
  [1022] = 1,
    ACTIONS(166), 1,
      anon_sym_COLON,
  [1026] = 1,
    ACTIONS(168), 1,
      anon_sym_COLON,
  [1030] = 1,
    ACTIONS(170), 1,
      sym_identifier,
  [1034] = 1,
    ACTIONS(172), 1,
      anon_sym_EQ,
  [1038] = 1,
    ACTIONS(174), 1,
      anon_sym_LBRACK,
  [1042] = 1,
    ACTIONS(176), 1,
      anon_sym_LBRACK,
  [1046] = 1,
    ACTIONS(178), 1,
      sym_identifier,
  [1050] = 1,
    ACTIONS(180), 1,
      sym_identifier,
  [1054] = 1,
    ACTIONS(182), 1,
      sym_identifier,
  [1058] = 1,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
  [1062] = 1,
    ACTIONS(186), 1,
      sym_identifier,
  [1066] = 1,
    ACTIONS(188), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 128,
  [SMALL_STATE(7)] = 160,
  [SMALL_STATE(8)] = 192,
  [SMALL_STATE(9)] = 224,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 288,
  [SMALL_STATE(12)] = 320,
  [SMALL_STATE(13)] = 346,
  [SMALL_STATE(14)] = 372,
  [SMALL_STATE(15)] = 398,
  [SMALL_STATE(16)] = 424,
  [SMALL_STATE(17)] = 450,
  [SMALL_STATE(18)] = 476,
  [SMALL_STATE(19)] = 501,
  [SMALL_STATE(20)] = 516,
  [SMALL_STATE(21)] = 531,
  [SMALL_STATE(22)] = 546,
  [SMALL_STATE(23)] = 571,
  [SMALL_STATE(24)] = 586,
  [SMALL_STATE(25)] = 605,
  [SMALL_STATE(26)] = 620,
  [SMALL_STATE(27)] = 645,
  [SMALL_STATE(28)] = 662,
  [SMALL_STATE(29)] = 682,
  [SMALL_STATE(30)] = 694,
  [SMALL_STATE(31)] = 706,
  [SMALL_STATE(32)] = 718,
  [SMALL_STATE(33)] = 730,
  [SMALL_STATE(34)] = 742,
  [SMALL_STATE(35)] = 756,
  [SMALL_STATE(36)] = 768,
  [SMALL_STATE(37)] = 780,
  [SMALL_STATE(38)] = 792,
  [SMALL_STATE(39)] = 804,
  [SMALL_STATE(40)] = 820,
  [SMALL_STATE(41)] = 831,
  [SMALL_STATE(42)] = 842,
  [SMALL_STATE(43)] = 853,
  [SMALL_STATE(44)] = 864,
  [SMALL_STATE(45)] = 877,
  [SMALL_STATE(46)] = 888,
  [SMALL_STATE(47)] = 899,
  [SMALL_STATE(48)] = 909,
  [SMALL_STATE(49)] = 917,
  [SMALL_STATE(50)] = 927,
  [SMALL_STATE(51)] = 935,
  [SMALL_STATE(52)] = 945,
  [SMALL_STATE(53)] = 955,
  [SMALL_STATE(54)] = 965,
  [SMALL_STATE(55)] = 975,
  [SMALL_STATE(56)] = 982,
  [SMALL_STATE(57)] = 989,
  [SMALL_STATE(58)] = 996,
  [SMALL_STATE(59)] = 1001,
  [SMALL_STATE(60)] = 1008,
  [SMALL_STATE(61)] = 1013,
  [SMALL_STATE(62)] = 1018,
  [SMALL_STATE(63)] = 1022,
  [SMALL_STATE(64)] = 1026,
  [SMALL_STATE(65)] = 1030,
  [SMALL_STATE(66)] = 1034,
  [SMALL_STATE(67)] = 1038,
  [SMALL_STATE(68)] = 1042,
  [SMALL_STATE(69)] = 1046,
  [SMALL_STATE(70)] = 1050,
  [SMALL_STATE(71)] = 1054,
  [SMALL_STATE(72)] = 1058,
  [SMALL_STATE(73)] = 1062,
  [SMALL_STATE(74)] = 1066,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_reference, 1, 0, 2),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 5),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 8),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 9),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_definition, 4, 0, 4),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_type, 1, 0, 2),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 6, 0, 14),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_type, 4, 0, 11),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 3, 0, 7),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_type, 3, 0, 6),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_type, 4, 0, 11),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 5, 0, 12),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_declaration, 4, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_alias_declaration, 4, 0, 4),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uninterpreted_type_declaration, 2, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 13),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type_field, 3, 0, 10),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2, 0, 0),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 15), SHIFT_REPEAT(10),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_type_repeat1, 2, 0, 15),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_definition, 4, 0, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_definition, 5, 0, 1),
  [164] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_quint(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "quint",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
